# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

media_player:
  - platform: yamaha
    host: 192.168.68.84
    name: "Yamaha Wohnzimmer"

input_boolean:
  party_modus:
    name: Party Modus
    icon: mdi:party-popper
  badtunna_override:
    name: Badtunna Pumpe Manuell
    icon: mdi:pump

input_button:
  badtunna_6h:
    name: Pumpe 6 Stunden
    icon: mdi:pump

input_select:
  terrasse_sender:
    name: Terrasse Sender
    options:
      - Bandit Rock
      - RIX FM
      - Mix Megapol
      - Star FM
    initial: Bandit Rock
    icon: mdi:radio

